# Generated by Django 5.1.6 on 2025-02-11 05:52

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_post_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='blog/default/profile_default.webp', null=True, upload_to=blog.models.blogger_name_dict),
        ),
    ]
