# Generated by Django 5.1.6 on 2025-02-13 08:23

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_comment_created_at_remove_like_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.blogger_name_dict),
        ),
    ]
