# Generated by Django 5.1.6 on 2025-02-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.ImageField(default=2, upload_to='categories_logo/'),
            preserve_default=False,
        ),
    ]
